### PR TITLE
feat: diagnostics

### PR DESCRIPTION
**Pull request by reinzor**
https://github.com/SICKAG/sick_safetyscanners2/issues/27

Diagnosed publisher, same as https://github.com/SICKAG/sick_safetyscanners2/pull/26
Sensor state diagnostics ROS1 functionality

### CODE REVIEW

**Comment by reinzor** [comment]
Not sure whether this is the desired implementation for the LifeCycle node:

Not configured: no diagnostics
Configured: no diagnostics
Activated: Regular diagnostics

**Comment by reinzor** [comment]
Dependent on https://github.com/SICKAG/sick_safetyscanners_base/pull/22 for correct checksum diagnostics

**Comment by reinzor** [comment]
ping @puck-fzi

**Comment by puck-fzi** [comment]
I scheduled the review and tests for next week, so I will come back to you then.

**Comment by puck-fzi** [comment]
okay, this appeared to be due to a secondary instance publishing stale data, works fine in a clean test suit.
I will commence a few more tests and if they all seem to work I will merge it. Thanks for your efforts.

**Comment by puck-fzi** [comment]
Merged

**Comment by reinzor** [comment]
Great thanks!

**Pull request merged**
