### PR TITLE
refactor: combine Node and LifeCycle node implementations

### PR DESCRIPTION
**Pull request by reinzor**
Also added ros2 clang format file to auto format code. #27

### CODE REVIEW

**Comment by reinzor** [comment]
ping @puck-fzi

**Comment by puck-fzi** [comment]
I am out of the office until the beginning of October, but will be able to test the PR then. Thanks for submitting it.

**Comment by puck-fzi** [comment]
From the code base it looks fine in my opinion. There are still some tests with hardware outstanding from my side before I will merge it. Thank you a lot for the refactoring! I will try to merge it as soon as I can

**Comment by reinzor** [comment]
@puck-fzi any updates on this?

**Comment by puck-fzi** [comment]
Currently testing it, so if nothing appears, I will push it today

**Comment by puck-fzi** [comment]
Which clang-format version did you use? Currently, I get a few style changes when I apply clang-format.

**Comment by reinzor** [comment]
> Which clang-format version did you use? Currently, I get a few style changes when I apply clang-format.

$ clang-format --version
Ubuntu clang-format version 14.0.0-1ubuntu1.1

**Pull request merged**
