### PR TITLE
Implement lifecycle node

### PR DESCRIPTION
**Pull request by guilyx**
Solves #9 

Side note: we had issues with the sick scanner node crashing with an error -11 and reported it on issue #8. This is solved when using a lifecycle node where we call configure then activate using `ros2 lifecycle set /name_of_the_node configure && ros2 lifecycle set /name_of_the_node activate` or using navigation2's lifecycle manager node.

### CODE REVIEW

**Comment by puck-fzi** [comment]
Hi, thanks for sharing this. It looks like there are some code duplication now between the classic node and lifecycle node.
i will put a TODO, to refactor this in the future. however I will test and check the lifecycle node as is and merge it probably in two weeks, when I had access to a scanner. First brief glance at the PR looks promising

**Comment by guilyx** [comment]
I could work on the duplication, but it wouldn't be before early August. Agreed that this is something to do!

**Comment by guilyx** [comment]
@puck-fzi Any update on this ?

**Comment by puck-fzi** [comment]
Hi, sorry I didn't get around to Testing it before my Holidays. Will do that as soon as i get back. Sorry for the delay.

**Comment by puck-fzi** [comment]
Hi, I finally got around to testing it. Working as expected. There are two minor things I would like to be in the PR. Could you add a brief description to the readme on how to start and and activate the node with the lifecycle.

Second: when only doing the configure step, there will be a lot of warnings, that messages are tried to being published. Since I am not that familiar with lifecycle Nodes maybe you know how to best resolve this.
`[sick_safetyscanners2_lifecycle_node-1] [WARN] [1628500948.017306622] [LifecyclePublisher]: Trying to publish message on the topic '/scan', but the publisher is not activated`

Otherwise I deem it ready to be merged, with the open future to do of refactoring it, that both lifecycle and non lifecycle node don't have that much code duplication.

**Comment by guilyx** [comment]
@puck-fzi Latest changes should prevent the warnings from happening, tell me if it does on your side.

**Pull request merged**
